from selenium import webdriver
import pyautogui
import time

options = webdriver.ChromeOptions()
options.add_experimental_option('excludeSwitches',['enable-logging'])

driver2 = webdriver.Chrome(options=options) 
driver2.implicitly_wait(20)     
driver1 = webdriver.Chrome(options=options) 
driver1.implicitly_wait(20)    

def test_privy_login():
    driver1.get("https://stg-oauth.privy.id/login?client_id=v5SCIvXPW1ZO7LLj_Fu2Vj-RIkKUBjR_qkvNymBg4Co&redirect_uri=http%3A%2F%2Flocalhost%2Fauth%2Fcallback&response_type=code&state=eyJyZWRpcmVjdFVybCI6Ii9sb2dpbi9wcml2eSJ9&scope=public")
    driver1.find_element_by_name("user[privyId]").send_keys("HJF9731")
    time.sleep(1)
    driver1.find_element_by_css_selector("button.btn-alt").click()
    driver1.find_element_by_css_selector("button.btn-alt").click()
    time.sleep(1)
    driver1.find_element_by_name("user[secret]").send_keys("aha84c4")
    time.sleep(1)
    driver1.find_element_by_css_selector("button.btn-alt").click()
    driver1.find_element_by_css_selector("button.btn-alt").click()
    time.sleep(3)

def test_privy_analytics():
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div/div/div[1]/div[2]/div/div/div[1]/input[1]').click()
    time.sleep(4)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div/div/div[1]/div[2]/div/div/div[1]/input[1]').clear()
    time.sleep(3)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div/div/div[1]/div[2]/div/div/div[1]/input[1]').send_keys("testing senin")
    time.sleep(2)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(2)                 

def test_privy_subscriberlist():
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[1]/nav/div[1]/div[2]/div[1]/div[1]/div[2]/div').click()
    time.sleep(2)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[1]/nav/div[1]/div[2]/div[1]/div[2]/a[1]').click()
    time.sleep(2)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[3]/div/div[1]/div/div/div/div[1]/input').send_keys("subscriber example")
    time.sleep(2)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[3]/div/div[2]/div/div/div/div[1]/div[1]').click()
    time.sleep(2)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div[2]/div').click()
    time.sleep(2)
    driver1.find_element_by_xpath('//*[@id="dashboard-app"]/div/main/div/div[1]/div/button/span').click()
    time.sleep(3)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/span/div/div[1]/div[1]/div/div[2]/button/span').click()
    time.sleep(2)

    pyautogui.write("tes.jpg")
    pyautogui.press("enter") 
    time.sleep(4)

    #npwp
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div/span/div/div[1]/div[2]/form/div[2]/div/div/span/div/div/div[1]/div/input').send_keys("000000000000022")
    time.sleep(2)
    driver1.find_element_by_xpath('//*[@id="dashboard-content"]/div/span/div/div[1]/div[2]/form/div[2]/button[1]/span').click()
    time.sleep(4)

    pyautogui.write("tes.jpg")
    pyautogui.press("enter") 
    time.sleep(4)

    #nama
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div/span/div/div[1]/div[2]/form/div[4]/div/span/div/div/div[1]/div/input').send_keys("test")
    time.sleep(2)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div/span/div/div[1]/div[2]/form/div[6]/div/span/div/div/div[1]/div/input').send_keys("089507747573")
    time.sleep(2)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div/span/div/div[1]/div[2]/form/div[8]/div/span/div/div/div/div/textarea').send_keys("jakarta")
    time.sleep(2)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div/span/div/div[1]/div[2]/form/div[12]/div/span/div/div/div[1]/div/input').send_keys("HJF9731")
    time.sleep(2)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div[2]/form/div[20]/div/div/div[2]/div/span/div/div/div/div/input').send_keys("product-dendy")
    time.sleep(2)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div[2]/form/div[20]/div/div/div[4]/div/span/div/div/div/div/input').send_keys("project-dendy")
    time.sleep(2)
    #button next tahap 1
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[2]/button').click()
    time.sleep(2)
    #addmoredocument
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div[1]/div[2]/button/span/i').click()
    time.sleep(2)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/span/div/div[1]/div[2]/form/div/button[2]/span').click()
    time.sleep(2)

    pyautogui.write("tes.pdf")
    pyautogui.press("enter") 
    time.sleep(4)

    #button next tahap 2
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[2]/button[2]/span').click()
    time.sleep(2)
    #button next tahap 3
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[2]/button[2]/span').click()
    time.sleep(4)
    #button next tahap 4
    driver1.find_element_by_xpath("//div[@id='dashboard-content']/div/div[3]/div[4]/button[2]/span").click()
    time.sleep(5)           
    driver1.find_element_by_css_selector("i.v-icon.notranslate.mdi.mdi-close.theme--light").click()
    time.sleep(20)

def test_privy_changerequest():
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div/nav/div[1]/div[2]/div[1]/div[2]/a[2]/div').click()
    time.sleep(2)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[1]/div[1]/div/div[1]/div/div/div/div[1]/input').send_keys("tes")

def test_privy_invoice():
    driver1.find_element_by_link_text('Invoice').click()
    time.sleep(2)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div/div[1]/div/div[1]/div/div/div/div[1]/input').send_keys("2022/INV/SUBE3AB4C/12-1")
    time.sleep(2)                 

def test_privy_user():
    driver1.find_element_by_link_text("User").click()
    time.sleep(2)
    driver1.find_element_by_css_selector("[test-id='btn:user/add']").click()
    time.sleep(1)
    driver1.find_element_by_css_selector("[test-id='input:user/add-dialog/privyid']").send_keys("tes")
    time.sleep(1)
    driver1.find_element_by_css_selector("[test-id='input:user/add-dialog/name']").send_keys("tes")
    time.sleep(1)                         
    driver1.find_element_by_css_selector("[test-id='btn:user/add-dialog/save']").click()
    time.sleep(5)
    driver1.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/span/div[1]/div[1]/div/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(2)

def test_privy_enterprise():
    driver1.find_element_by_link_text("Enterprise").click()
    time.sleep(2)
    driver1.find_element_by_css_selector("[test-id='input:filter/enterprise/company-name']").send_keys("test")
    time.sleep(3)                 

def test_privy_activitylog():
    driver1.find_element_by_link_text("Activity Log").click()
    time.sleep(2)
    driver1.find_element_by_css_selector("[test-id='input:filter/activity-log/name']").send_keys("Get List Actifity Log Privy")
    time.sleep(5)

def test_privy_notification():
    driver1.find_element_by_css_selector('i.v-icon.notranslate.mdi.mdi-bell-outline.theme--light').click()
    time.sleep(3)
    #driver1.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/footer/button/span').click()
    #time.sleep(1)   
    driver1.minimize_window()

def test_subscriber_login():
    driver2.get("https://stg-oauth.privy.id/login?client_id=v5SCIvXPW1ZO7LLj_Fu2Vj-RIkKUBjR_qkvNymBg4Co&redirect_uri=http%3A%2F%2Flocalhost%2Fauth%2Fcallback&response_type=code&state=eyJyZWRpcmVjdFVybCI6Ii9sb2dpbi92ZW5kcG9pbnQifQ%3D%3D&scope=public")
    driver2.find_element_by_name("user[privyId]").send_keys("HJF9731")
    time.sleep(1)
    driver2.find_element_by_css_selector("button.btn-alt").click()
    driver2.find_element_by_css_selector("button.btn-alt").click()
    time.sleep(1)
    driver2.find_element_by_name("user[secret]").send_keys("aha84c4")
    time.sleep(1)
    driver2.find_element_by_css_selector("button.btn-alt").click()
    driver2.find_element_by_css_selector("button.btn-alt").click()
    time.sleep(5)

def test_subscriber_actor():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/main/div/div/div[2]/div/div/div[3]/div/div/div[1]/div/div/div/div/div[1]/input').send_keys("Subscriber Example")
    time.sleep(1)
    driver2.find_element_by_css_selector(".v-treeview-node.v-treeview-node--leaf.v-treeview-node--click").click()
    time.sleep(5)

def test_subscriber_analytics():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div/div/div[2]/div[3]/div[2]/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(3)

def test_subscriber_uploaddoc():
    driver2.find_element_by_link_text("Upload Doc").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[2]/div/div/span/div/div/div[1]/div/input').send_keys("tes")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/button/div[1]/div/div/div[2]/button/span').click()
    time.sleep(2)
    pyautogui.write("tes.pdf")
    pyautogui.press("enter") 
    time.sleep(5)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[1]/div/div/div[2]/div/div/div[1]/div[3]/div/div/div/div[1]/div/div[1]').click()
    time.sleep(2)          
    #click document categories
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[1]/div/span/div/div/div[1]/div[1]/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_id("documents[0].category1").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[2]/div/span/div/div/div[1]/div[1]/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_id("documents[0].sub_category1").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[3]/div/div/span/div/div/div/div/input').send_keys("tes")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[5]/div/div/span/div/div/div/div/textarea').send_keys("tes")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[3]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_id("user_name").send_keys("Hendrikus juan")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div').click()
    time.sleep(2)
    #button 2
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div[2]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[2]/div/div[3]/div/table/tbody/tr/td[5]/div/div/div/div/div').click()
    time.sleep(2)
    #button 3
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[2]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_css_selector("[test-id='btn:upload-doc/step4/signer/SUBSCRIBER/HJF9731']").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[2]/div/div/div[3]/div[2]/div/button[1]/span/i').click()
    time.sleep(2)                 
    driver2.find_element_by_css_selector("[test-id='btn:next-or-sumbit']").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[3]/button[2]/span').click()
    time.sleep(23)

def test_subscriber_waitingsigner():
    driver2.find_element_by_link_text("Waiting Signer").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)                  
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)
    driver2.find_element_by_css_selector('i.v-icon.notranslate.mdi.mdi-dots-horizontal.theme--light').click()
    time.sleep(1)
    driver2.find_element_by_css_selector("[test-id='btn:waiting-signer/list/0/action/details']").click()
    time.sleep(9)

def test_subscriber_approve():
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/nav/div[1]/div[2]/div[1]/div[2]/a[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)                 
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)        
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)      
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1)   
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)                       
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)

def test_subscriber_reject():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/nav/div[1]/div[2]/div[1]/div[2]/a[2]/div').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)  
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1) 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)     
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)

def test_subscriber_drop():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/nav/div[1]/div[2]/div[1]/div[2]/a[3]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)  
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1) 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)    
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)

def test_subscriber_settings():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/nav/div[1]/div[2]/div[3]/div[1]/div[2]/div').click()
    time.sleep(1)

def test_subscriber_subscriberuser():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/nav/div[1]/div[2]/div[3]/div[2]/a[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)

def test_subscriber_product():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/nav/div[1]/div[2]/div[3]/div[2]/a[2]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[1]/div/button/span').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[1]/div/div/div/span/div/div/div[1]/div/input').send_keys("tes 95")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[2]/div[2]/div[1]/div/span/div/div/div[1]/div/input').send_keys("HJF9731")
    time.sleep(4)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[3]/div/div/span/div/div/div/div[1]/div[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div[2]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('//*[@id="dashboard-app"]/div[3]/div/div/div[2]/div/form/div[4]/div/button[2]/span').click()
    time.sleep(5)       
    driver2.find_element_by_xpath("(//button[@id='btn:base-dialog/close']/span/i)[2]").click()
    time.sleep(2)                   
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[3]/div/div[1]/div/div/div/div[1]/input').send_keys("tes 95")
    time.sleep(1)          
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[3]/div/div[3]/div/div/div[1]/div[1]/div[1]').click()
    time.sleep(1)         
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[5]/div/div[3]/div/div').click()
    time.sleep(2)                 

def test_subscriber_seelistproject():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[4]/div[2]/div/div/div/div[2]/div/div[5]/div/button[2]/span').click()
    time.sleep(1)                              
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[1]/div/button/span').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[2]/div/span/div/div/span/div/div/div[1]/div/input').send_keys("tes 95")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[3]/div[2]/div[1]/div/span/div/div/div[1]/div/input').send_keys("HJF9731")
    time.sleep(4)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[5]/div/button[2]/span').click()
    time.sleep(5)
    driver2.find_element_by_xpath("(//button[@id='btn:base-dialog/close']/span/i)[2]").click()
    time.sleep(2) 

def test_subscriber_user():
    driver2.find_element_by_link_text("User").click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div/div/div/div[1]/div[2]/button/span').click()
    time.sleep(3)                        
    driver2.find_element_by_xpath("//div[@id='dashboard-app']/div[3]/div/div/div[2]/div/form/div[2]/div/div/span/div/div/div/div/input").send_keys("DYD7573")
    time.sleep(3)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[4]/div/span/div/div/div/div/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[6]/div/span/div/div/div/div/input').send_keys("tes")
    time.sleep(1)             
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[7]/div[2]/span/div/div/div/div[1]/div[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[12]/div/button[2]').click()
    time.sleep(6)
    driver2.find_element_by_css_selector("i.v-icon.notranslate.mdi.mdi-close.theme--light").click()
    time.sleep(3)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div/div/div/div[1]/input').send_keys("Dendy")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[1]/div[2]/div/div/div/div[2]/div/div/div[1]/table/tbody/tr/td[11]/button/span/i').click()
    time.sleep(3)              
    driver2.find_element_by_css_selector("[test-id='btn:settings/user/add-user/list/0/action/delete']").click()
    time.sleep(1)
    driver2.find_element_by_xpath("//div[2]/div[2]/button/span").click()
    time.sleep(5)                 
    driver2.find_element_by_css_selector("i.v-icon.notranslate.mdi.mdi-close.theme--light").click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[1]/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)
    driver2.find_element_by_css_selector("[test-id='btn:settings/user/change-representative/change-representative']").click()
    time.sleep(1)
    driver2.find_element_by_css_selector("[test-id='input:settings/user/change-request-dialog/privyid']").send_keys("DYD7573")
    time.sleep(4)
    driver2.find_element_by_css_selector("[test-id='btn:settings/user/change-request-dialog/save']").click()
    time.sleep(3)
    driver2.find_element_by_css_selector("i.v-icon.notranslate.mdi.mdi-close.theme--light").click()
    time.sleep(1)

def test_subscriber_inviteuser():
    driver2.find_element_by_link_text("Invite User").click()
    time.sleep(2)
    driver2.find_element_by_css_selector("[test-id='input:filter/invite-user/name']").send_keys("Dendy")
    time.sleep(1)                       

def test_subscriber_activitylog():
    driver2.find_element_by_link_text("Activity Log").click()
    time.sleep(2)
    driver2.find_element_by_css_selector("[test-id='input:filter/activity-log/name']").send_keys("Get List User Subscriber")
    time.sleep(2)

def test_subscriber_invoice():
    driver2.find_element_by_css_selector("[test-id='nav:/dashboard/invoice']").click()
    time.sleep(3)

def test_subscriber_notification():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/header/div/button/span/div/span/i').click()
    time.sleep(1)
    #driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div[1]/button/span').click()
    #time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/footer/button/span').click()
    time.sleep(1)

def test_subscriber_logout():
    driver2.find_element_by_xpath("//div[@id='dashboard-app']/div/header/div/div[5]/div/div[2]/div[2]").click()
    time.sleep(4)
    driver2.find_element_by_css_selector("[test-id='btn:logout']").click()
    time.sleep(3) 

def test_product_actor():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/main/div/div/div[2]/div/div/div[2]/div[2]/button/span').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/main/div/div/div[2]/div/div/div[3]/div/div/div[1]/div/div/div/div/div[1]/input').send_keys("Product Example")
    time.sleep(1)
    driver2.find_element_by_css_selector(".v-treeview-node.v-treeview-node--leaf.v-treeview-node--click").click()
    time.sleep(4)

def test_product_uploaddoc():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[2]/div/div/span/div/div/div[1]/div/input').send_keys("tes")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/button/div[1]/div/div/div[2]/button/span').click()
    time.sleep(2)
    pyautogui.write("tes.pdf")
    pyautogui.press("enter") 
    time.sleep(4)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[1]/div/div/div[2]/div/div/div[1]/div[3]/div/div/div/div[1]/div/div[1]').click()
    time.sleep(2)          
    #click document categories
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[1]/div/span/div/div/div[1]/div[1]/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_id("documents[0].category1").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[2]/div/span/div/div/div[1]/div[1]/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_id("documents[0].sub_category1").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[3]/div/div/span/div/div/div/div/input').send_keys("tes")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[5]/div/div/span/div/div/div/div/textarea').send_keys("tes")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[3]/button[2]/span').click()
    time.sleep(4)
    driver2.find_element_by_id("user_name").send_keys("Hendrikus juan")
    time.sleep(4)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div').click()
    time.sleep(2)
    #button 2
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div[2]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[2]/div/div[3]/div/table/tbody/tr/td[5]/div/div/div/div/div').click()
    time.sleep(2)
    #button 3
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[2]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_css_selector("[test-id='btn:upload-doc/step4/signer/SUBSCRIBER/HJF9731']").click()
    time.sleep(3)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[2]/div/div/div[3]/div[2]/div/button[1]/span/i').click()
    time.sleep(2)                 
    driver2.find_element_by_css_selector("[test-id='btn:next-or-sumbit']").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[3]/button[2]/span').click()
    time.sleep(23)

def test_product_waitingsigner():
    driver2.find_element_by_link_text("Waiting Signer").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)                  
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)
    driver2.find_element_by_css_selector('i.v-icon.notranslate.mdi.mdi-dots-horizontal.theme--light').click()
    time.sleep(1)
    driver2.find_element_by_css_selector("[test-id='btn:waiting-signer/list/0/action/details']").click()
    time.sleep(15)

def test_product_approve():
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/nav/div[1]/div[2]/div[1]/div[2]/a[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)                 
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)        
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)      
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1)   
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)                       
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)

def test_product_reject():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/nav/div[1]/div[2]/div[1]/div[2]/a[2]/div').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)  
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1) 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)     
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)

def test_product_drop():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/nav/div[1]/div[2]/div[1]/div[2]/a[3]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)  
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1) 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)    
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)

def test_product_settings():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/nav/div[1]/div[2]/div[3]/div[1]/div[2]/div').click()
    time.sleep(1)          

def test_product_project():
    driver2.find_element_by_link_text("Project").click()
    time.sleep(1)                              
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[1]/div/button/span').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[2]/div/span/div/div/span/div/div/div[1]/div/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[3]/div[2]/div[1]/div/span/div/div/div[1]/div/input').send_keys("HJF9731")
    time.sleep(3)            
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[4]/div/div/span/div').click()
    time.sleep(1)                       
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div[2]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[5]/div/button[2]/span').click()
    time.sleep(5)
    driver2.find_element_by_xpath("(//button[@id='btn:base-dialog/close']/span/i)[2]").click()
    time.sleep(2) 

def test_product_user():
    driver2.find_element_by_link_text("User").click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div/div/div/div[1]/div[2]/button/span').click()
    time.sleep(3)                        
    driver2.find_element_by_xpath("//div[@id='dashboard-app']/div[3]/div/div/div[2]/div/form/div[2]/div/div/span/div/div/div/div/input").send_keys("DYD7573")
    time.sleep(3)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[4]/div/span/div/div/div/div/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[6]/div/span/div/div/div/div/input').send_keys("tes")
    time.sleep(1)             
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[7]/div[2]/span/div/div/div/div[1]/div[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[12]/div/button[2]').click()
    time.sleep(5)
    driver2.find_element_by_css_selector("i.v-icon.notranslate.mdi.mdi-close.theme--light").click()
    time.sleep(1)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div/div/div/div[1]/input').send_keys("Dendy")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[1]/div[2]/div/div/div/div[2]/div/div/div[1]/table/tbody/tr/td[11]/button/span/i').click()
    time.sleep(3)              
    driver2.find_element_by_css_selector("[test-id='btn:settings/user/add-user/list/0/action/delete']").click()
    time.sleep(1)
    driver2.find_element_by_xpath("//div[2]/div[2]/button/span").click()
    time.sleep(5)                 
    driver2.find_element_by_css_selector("i.v-icon.notranslate.mdi.mdi-close.theme--light").click()
    time.sleep(1)

def test_product_inviteuser():
    driver2.find_element_by_link_text("Invite User").click()
    time.sleep(2)
    driver2.find_element_by_css_selector("[test-id='input:filter/invite-user/name']").send_keys("Dendy")
    time.sleep(1)                       

def test_product_activitylog():
    driver2.find_element_by_link_text("Activity Log").click()
    time.sleep(2)
    driver2.find_element_by_css_selector("[test-id='input:filter/activity-log/name']").send_keys("Get List User Subscriber")
    time.sleep(1)

def test_product_notification():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/header/div/button/span/div/span/i').click()
    time.sleep(1)
    #driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div[1]/button/span').click()
    #time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/footer/button/span').click()
    time.sleep(2)
    driver2.minimize_window()
    time.sleep(1)

def test_product_logout():
    driver2.find_element_by_xpath("//div[@id='dashboard-app']/div/header/div/div[5]/div/div[2]/div[2]").click()
    time.sleep(4)
    driver2.find_element_by_css_selector("[test-id='btn:logout']").click()
    time.sleep(3) 

def test_project_actor():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/main/div/div/div[2]/div/div/div[2]/div[3]/button/span').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/main/div/div/div[2]/div/div/div[3]/div/div/div[1]/div/div/div/div/div[1]/input').send_keys("Project Example")
    time.sleep(1)
    driver2.find_element_by_css_selector(".v-treeview-node.v-treeview-node--leaf.v-treeview-node--click").click()
    time.sleep(4)

def test_project_uploaddoc():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[5]/div/span/div/div/div[1]/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_id("vendor_idVEN1AB3CD").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/button/div[1]/div/div/div[2]/button/span').click()
    time.sleep(2)

    pyautogui.write("tes.pdf")
    pyautogui.press("enter") 
    time.sleep(4)

    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[1]/div/div/div[2]/div/div/div[1]/div[3]/div/div/div/div[1]/div/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[1]/div/span/div/div/div[1]/div[1]/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_id("documents[0].category1").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[2]/div/span/div/div/div[1]/div[1]/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_id("documents[0].sub_category1").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[3]/div/div/span/div/div/div/div/input').send_keys("Tes Dendy")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[5]/div/div/span/div/div/div/div/textarea').send_keys("Tes Dendy")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[3]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[2]/div/form/div/div[2]/div/div/div/div/div[1]/input[1]').send_keys("Hendrikus Juan")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[2]/div/form/div/div[2]/div/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[2]/div/form/div/div[2]/div/div/div/div/div[1]/input[1]').send_keys("Dendy")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(2)
    #button next addrecipcient 2
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div[2]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[2]/div/div[3]/div/table/tbody/tr[1]/td[5]/div/div/div/div/div').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[2]/div/div[3]/div/table/tbody/tr[2]/td[5]/div/div/div/div/div').click()
    time.sleep(2)
    #button next 3
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[2]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[3]/div[1]/div[2]/div/div[2]/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[2]/div/div/div[3]/div[2]/div/button[1]/span/i').click()
    time.sleep(2)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[3]/div[2]/div[2]/div/div[2]/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[2]/div/div/div[3]/div[3]/div/button[1]/span/i').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[2]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[3]/button[2]/span').click()
    time.sleep(23)

def test_project_waitingsigner():
    driver2.find_element_by_link_text("Waiting Signer").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("Project Example")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)                  
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)
    driver2.find_element_by_css_selector('i.v-icon.notranslate.mdi.mdi-dots-horizontal.theme--light').click()
    time.sleep(1)
    driver2.find_element_by_css_selector("[test-id='btn:waiting-signer/list/0/action/details']").click()
    time.sleep(8)

def test_project_approve():
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/nav/div[1]/div[2]/div[1]/div[2]/a[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)                 
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)        
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)      
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1)   
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)                       
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)

def test_project_reject():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/nav/div[1]/div[2]/div[1]/div[2]/a[2]/div').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)  
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1) 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)     
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)

def test_project_drop():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/nav/div[1]/div[2]/div[1]/div[2]/a[3]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)  
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1) 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)    
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)

def test_project_settings():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/nav/div[1]/div[2]/div[3]/div[1]/div[2]/div').click()
    time.sleep(1)    

def test_project_vendor():
    driver2.find_element_by_link_text("Vendor").click()
    time.sleep(2)
    driver2.find_element_by_css_selector("[test-id='btn:settings/vendor/add-vendor']").click()
    time.sleep(2)
    #npwp
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[3]/form/div/div[2]/div/div/div/div/span/div/div/div[1]/div/input').send_keys("2200000000000000")
    time.sleep(2)
    driver2.find_element_by_xpath('//*[@id="dashboard-app"]/div[3]/div/div/div[3]/form/div/div[2]/div/button[1]/span').click()
    time.sleep(2)
    pyautogui.write("tes.jpg")
    pyautogui.press("enter") 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[3]/form/div/div[1]/div/div[2]/button/span').click()
    time.sleep(2)
    pyautogui.write("tes.jpg")
    pyautogui.press("enter") 
    #nama
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[3]/form/div/div[3]/div/div/span/div/div/div[1]/div/input').send_keys("Test")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[3]/form/div/div[4]/div/div/span/div/div/div/div/input').send_keys("021507747573")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[3]/form/div/div[5]/div/div/span/div/div/div/div/textarea').send_keys("Pamulang")
    time.sleep(2)
    #with privyid
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[3]/form/div/div[6]/form/div/div[4]/div/div/span/div/div/div[1]/div/input').send_keys("HJF9731")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[3]/div/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/span/div/div[1]/div[1]/div/div[3]/button/span/i').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/span/div/div[1]/div[2]/form/div/button[2]/span').click()
    time.sleep(2)
    pyautogui.write("tes.pdf")
    pyautogui.press("enter") 
    time.sleep(4)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/span/div/div[2]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_css_selector("i.v-icon.notranslate.mdi.mdi-close.theme--light").click()
    time.sleep(3)
    driver2.find_element_by_css_selector("[test-id='input:filter/vendor/name']").send_keys("test")
    time.sleep(1)                       
    driver2.find_element_by_css_selector("i.v-icon.notranslate.mdi.mdi-dots-horizontal.theme--light").click()
    time.sleep(1)
    driver2.find_element_by_css_selector("[test-id='link:settings/vendor/list/0/action/details']").click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div/div/div[2]/div/div/div/div/button/span/i').click()
    time.sleep(1)

def test_project_changerequest():
    driver2.find_element_by_link_text("Change Request").click()
    time.sleep(2)
    driver2.find_element_by_css_selector("[test-id='input:filter/subscriber/name']").send_keys("test")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[1]/div/div[2]/div/div/div/div[1]/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div[2]/div').click()
    time.sleep(4)

def test_project_user():
    driver2.find_element_by_link_text("User").click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div/div/div/div[1]/div[2]/button/span').click()
    time.sleep(3)                        
    driver2.find_element_by_xpath("//div[@id='dashboard-app']/div[3]/div/div/div[2]/div/form/div[2]/div/div/span/div/div/div/div/input").send_keys("AAA1393")
    time.sleep(3)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[4]/div/span/div/div/div/div/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[6]/div/span/div/div/div/div/input').send_keys("tes")
    time.sleep(1)             
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[7]/div[2]/span/div/div/div/div[1]/div[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[12]/div/button[2]').click()
    time.sleep(5)
    driver2.find_element_by_css_selector("i.v-icon.notranslate.mdi.mdi-close.theme--light").click()
    time.sleep(1)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div/div/div/div[1]/input').send_keys("Azzam")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[1]/div[2]/div/div/div/div[2]/div/div/div[1]/table/tbody/tr/td[11]/button/span/i').click()
    time.sleep(3)              
    driver2.find_element_by_css_selector("[test-id='btn:settings/user/add-user/list/0/action/delete']").click()
    time.sleep(1)
    driver2.find_element_by_xpath("//div[2]/div[2]/button/span").click()
    time.sleep(5)                 
    driver2.find_element_by_css_selector("i.v-icon.notranslate.mdi.mdi-close.theme--light").click()
    time.sleep(1)

def test_project_inviteuser():
    driver2.find_element_by_link_text("Invite User").click()
    time.sleep(2)
    driver2.find_element_by_css_selector("[test-id='input:filter/invite-user/name']").send_keys("Dendy")
    time.sleep(1)                       

def test_project_activitylog():
    driver2.find_element_by_link_text("Activity Log").click()
    time.sleep(2)
    driver2.find_element_by_css_selector("[test-id='input:filter/activity-log/name']").send_keys("Get List User Subscriber")
    time.sleep(1)

def test_project_notification():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/header/div/button/span/div/span/i').click()
    time.sleep(1)
    #driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div[1]/button/span').click()
    #time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/footer/button/span').click()
    time.sleep(2)

def test_project_logout():
    driver2.find_element_by_xpath("//div[@id='dashboard-app']/div/header/div/div[5]/div/div[2]/div[2]").click()
    time.sleep(4)
    driver2.find_element_by_css_selector("[test-id='btn:logout']").click()
    time.sleep(3) 

def test_vendor_actor():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/main/div/div/div[2]/div/div/div[2]/div[4]/button/span').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/main/div/div/div[2]/div/div/div[3]/div/div/div[1]/div/div/div/div/div[1]/input').send_keys("Vendor Example")
    time.sleep(1)
    driver2.find_element_by_css_selector(".v-treeview-node.v-treeview-node--leaf.v-treeview-node--click").click()
    time.sleep(5)

def test_vendor_uploaddoc():
    driver2.find_element_by_css_selector("[test-id='input:upload-doc/step1/doc-subject']").send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/button/div[1]/div/div/div[2]/button/span').click()
    time.sleep(3)
    pyautogui.write("tes.pdf")
    pyautogui.press("enter") 
    time.sleep(4)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[1]/div/div/div[2]/div/div/div[1]/div[3]/div/div/div/div[1]/div/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[1]/div/span/div/div/div[1]/div[1]/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_id("documents[0].category1").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[2]/div/span/div/div/div[1]/div[1]/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_id("documents[0].sub_category1").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[3]/div/div/span/div/div/div/div/input').send_keys("Tes Dendy")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[1]/div/form/div/div[6]/div/div/div/div/div[3]/div[5]/div/div/span/div/div/div/div/textarea').send_keys("Tes Dendy")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/span/div/div[3]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[2]/div/form/div/div[2]/div/div/div/div/div[1]/input[1]').send_keys("Hendrikus Juan")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[2]/div/form/div/div[2]/div/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[2]/div/form/div/div[2]/div/div/div/div/div[1]/input[1]').send_keys("Dendy")
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(2)
    #button next addrecipcient 2
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div[1]/main/div/div[2]/div[1]/div[2]/div[2]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[2]/div/div[3]/div/table/tbody/tr[1]/td[5]/div/div/div/div/div').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[2]/div/div[3]/div/table/tbody/tr[2]/td[5]/div/div/div/div/div').click()
    time.sleep(2)
    #button next 3
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[2]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[3]/div[1]/div[2]/div/div[2]/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[2]/div/div/div[3]/div[2]/div/button[1]/span').click()
    time.sleep(2)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[3]/div[2]/div[2]/div/div[2]/div[1]').click()
    time.sleep(2)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[2]/div/div/div[3]/div[3]/div/button[1]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[2]/div[2]/button[2]/span').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[3]/button[2]/span').click()
    time.sleep(23)

def test_vendor_waitingsigner():
    driver2.find_element_by_link_text("Waiting Signer").click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)                  
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)
    driver2.find_element_by_css_selector('i.v-icon.notranslate.mdi.mdi-dots-horizontal.theme--light').click()
    time.sleep(1)
    driver2.find_element_by_css_selector("[test-id='btn:waiting-signer/list/0/action/details']").click()
    time.sleep(15)

def test_vendor_approve():
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/nav/div[1]/div[2]/div[1]/div[2]/a[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)                 
    driver2.find_element_by_xpath('/html/body/div[1]/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)        
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)      
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1)   
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)                       
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)

def test_vendor_reject():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/nav/div[1]/div[2]/div[1]/div[2]/a[2]/div').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)  
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1) 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)     
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)

def test_vendor_drop():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/nav/div[1]/div[2]/div[1]/div[2]/a[3]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div[1]/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/input').send_keys("Category 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div/div/div/span').click()
    time.sleep(1)  
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div[1]/div[1]/div[1]/input').send_keys("Sub Category 1 1")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div/div/span').click()
    time.sleep(1) 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div/div[1]/div[1]/input[1]').send_keys("YES")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div/div/div/span').click()
    time.sleep(1)    
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[3]').click()
    time.sleep(1)

def test_vendor_settings():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/nav/div[1]/div[2]/div[3]/div[1]/div[2]/div').click()
    time.sleep(1)    

def test_vendor_user():
    driver2.find_element_by_link_text("User").click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div/div/div/div[1]/div[2]/button/span').click()
    time.sleep(3)                        
    driver2.find_element_by_xpath("//div[@id='dashboard-app']/div[3]/div/div/div[2]/div/form/div[2]/div/div/span/div/div/div/div/input").send_keys("AAA1393")
    time.sleep(3)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[4]/div/span/div/div/div/div/input').send_keys("tes")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[6]/div/span/div/div/div/div/input').send_keys("tes")
    time.sleep(1)             
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[7]/div[2]/span/div/div/div/div[1]/div[1]').click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[4]/div/div[1]').click()
    time.sleep(2)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div/div[2]/div/form/div[12]/div/button[2]').click()
    time.sleep(7)
    driver2.find_element_by_css_selector("i.v-icon.notranslate.mdi.mdi-close.theme--light").click()
    time.sleep(2)                 
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/main/div/div[2]/div[1]/div[1]/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div/div/div/div[1]/input').send_keys("Azzam")
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div/main/div/div[2]/div[1]/div[1]/div[2]/div/div/div/div[2]/div/div/div[1]/table/tbody/tr/td[11]/button/span/i').click()
    time.sleep(3)              
    driver2.find_element_by_css_selector("[test-id='btn:settings/user/add-user/list/0/action/delete']").click()
    time.sleep(1)
    driver2.find_element_by_xpath("//div[2]/div[2]/button/span").click()
    time.sleep(5)                 
    driver2.find_element_by_css_selector("i.v-icon.notranslate.mdi.mdi-close.theme--light").click()
    time.sleep(3)

def test_vendor_inviteuser():
    driver2.find_element_by_link_text("Invite User").click()
    time.sleep(3)
    driver2.find_element_by_css_selector("[test-id='input:filter/invite-user/name']").send_keys("Dendy")
    time.sleep(3)                       

def test_vendor_activitylog():
    driver2.find_element_by_link_text("Activity Log").click()
    time.sleep(2)
    driver2.find_element_by_css_selector("[test-id='input:filter/activity-log/name']").send_keys("Get List User Subscriber")
    time.sleep(1)

def test_vendor_notification():
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[1]/header/div/button/span/div/span/i').click()
    time.sleep(1)
    #driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div[1]/button/span').click()
    #time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/footer/button/span').click()
    time.sleep(2)

def test_vendor_subscriberdata():
    driver2.find_element_by_xpath("//div[@id='dashboard-app']/div/header/div/div[5]/div/div[2]/div[2]").click()
    time.sleep(1)
    driver2.find_element_by_xpath('/html/body/div/div/div/div/div[3]/div/div[1]/div[2]').click()
    time.sleep(3)
    driver2.find_element_by_css_selector('i.v-icon.notranslate.bg-secondary--icon.mdi.mdi-download.theme--light').click()
    time.sleep(4)

def test_vendor_logout():
    driver2.find_element_by_xpath("//div[@id='dashboard-app']/div/header/div/div[5]/div/div[2]/div[2]").click()
    time.sleep(3)
    driver2.find_element_by_css_selector("[test-id='btn:logout']").click()
    time.sleep(4) 